services:
  upload.s3.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionString:DefaultConnection=mongodb://mongodb:27017"
    ports:
      - "8080"
      - "8081"
    networks:
      - app-network
    
  ### Postgres
  postgresdb:
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: archives
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
 ### PgAdmin
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "ads.junio@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - 5050:80
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin